### ISSUE TITLE
048 tmc or tpeg

### ISSUE THREAD

**Issue by INH888** [Mr-MIBonk/M.I.B._More-Incredible-Bash#217]
Bro, can the software flash TPEG? That is, to update the real-time traffic information on the 048 AISIN head unit.

**Comment by harman-f** [comment]
Can you give more details on this?

**Comment by INH888** [comment]
> Can you give more details on this?

![820_ChtliGJqaXeAfruvAAd3fCx9ADE682](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/130017774/d0d0e1cf-0e01-48eb-82be-a459aaa33f36)
Like that, it shows real-time traffic information on the navigation

**Comment by catatonicChimp** [comment]
1. What country?

TPEG is a lot different to RDS-TMC in terms of implementation, there is set servers which the car/headunit vin has to authenticate against before data is returned... short answer is probably a no...

**Comment by INH888** [comment]
> 1. What country?
> 
> TPEG is a lot different to RDS-TMC in terms of implementation, there is set servers which the car/headunit vin has to authenticate against before data is returned... short answer is probably a no...

CHINA.
Dude, you mean it's not free?

**Comment by catatonicChimp** [comment]
Depends on the data supplier and the way its setup with VW
TMC-RDS is specifically over FM radio which makes it a lot easier to hack around since its a one way transaction and all the location data is stored locally. 

TPEG can be over either DAB+ Radio or more likely via IP (Wifi/Mobile Data) 
In the case of VW it appears all TPEG data comes via IP (Wifi/Mobile Data) and given the LTE icon in your photo above, it looks like you need a LTE connection for it to work. 

From my brief reading it requires to authenticate against a VW License server checking both VIN + License before it allows you to connect to the data provider, I believe it used to be Tomtom but that is the limit of my knowledge because VW never enabled it in my country. Even if I could hack it to work like some people tried on the Audi Forums it wouldn't work for me..  even if you get the config correct, you also need to hack a VIN into the radio that has a online entitlement already, and it not been expired, it also sounds like VW has blacklisted any unit that didn't originally come with a 3G/LTE modem integrated.

**Comment by harman-f** [comment]
![grafik](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/98130152/25cdcf56-3f47-40e3-92ba-32b26fb6c50c)

![grafik](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/98130152/d38d1eb4-40ec-4104-a5ad-204ec00ccd7c)

**Comment by INH888** [comment]
> Depends on the data supplier and the way its setup with VW TMC-RDS is specifically over FM radio which makes it a lot easier to hack around since its a one way transaction and all the location data is stored locally.
> 
> TPEG can be over either DAB+ Radio or more likely via IP (Wifi/Mobile Data) In the case of VW it appears all TPEG data comes via IP (Wifi/Mobile Data) and given the LTE icon in your photo above, it looks like you need a LTE connection for it to work.
> 
> From my brief reading it requires to authenticate against a VW License server checking both VIN + License before it allows you to connect to the data provider, I believe it used to be Tomtom but that is the limit of my knowledge because VW never enabled it in my country. Even if I could hack it to work like some people tried on the Audi Forums it wouldn't work for me.. even if you get the config correct, you also need to hack a VIN into the radio that has a online entitlement already, and it not been expired, it also sounds like VW has blacklisted any unit that didn't originally come with a 3G/LTE modem integrated.

To my knowledge, someone has achieved real-time traffic information feature on a non-SIM enabled Harman 048 head unit through the WLAN function in the navigation interface.  However, they did not provide a detailed explanation on how it was accomplished.

**Comment by INH888** [comment]
> ![grafik](https://user-images.githubusercontent.com/98130152/239949848-25cdcf56-3f47-40e3-92ba-32b26fb6c50c.png)
> 
> ![grafik](https://user-images.githubusercontent.com/98130152/239949982-d38d1eb4-40ec-4104-a5ad-204ec00ccd7c.png)

Bro, I apologize for my lack of proficiency with the program.  Has the program already been updated?  And if so, how can I use it?

**Comment by INH888** [comment]
> ![grafik](https://user-images.githubusercontent.com/98130152/239949848-25cdcf56-3f47-40e3-92ba-32b26fb6c50c.png)
> 
> ![grafik](https://user-images.githubusercontent.com/98130152/239949982-d38d1eb4-40ec-4104-a5ad-204ec00ccd7c.png)

Bro, I apologize for my lack of expertise with the program.  Has the program been updated?  And if so, could you please guide me on how to use it?

**Comment by harman-f** [comment]
No, just some strings I found in the existing files referencing `freeDAB-TPEG`

Get us a backup of such an improved unit ;)

**Comment by qf512415007** [comment]
这个怎么更新

**Comment by qf512415007** [comment]
> > Can you give more details on this?
> 
> 
> 
> ![820_ChtliGJqaXeAfruvAAd3fCx9ADE682](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/130017774/d0d0e1cf-0e01-48eb-82be-a459aaa33f36)
> 
> Like that, it shows real-time traffic information on the navigation
> 
> 

你最后找到方法没有

**Comment by isarrider** [comment]
Did this go somewhere?
